# -*- coding: utf-8 -*-
"""Test-to-speach-converter-Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17EhnGGG3rbkXbBZBBz03HJFksSjZatzc
"""

#@title Text to Speech Module
#!pip install gTTS

from gtts import gTTS
from datetime import datetime
import pytz

text_to_say="This is good resoure to study" # text to convert into audio
language='en'# gTTS support total 63 languages, here I am using english
folderPath="/content/" # for example - "/content/"

globalfilepath=""
def audioWithFileSave(text,lang,folderPath):
  global globalfilepath
  # Get the current time in Pacific Time
  pacific_time = datetime.now(pytz.timezone('America/Los_Angeles'))
  # Format the current time as a string
  formatted_time = pacific_time.strftime("%Y-%m-%d %H:%M:%S")
  gtts_obj=gTTS(text=text,lang=lang,slow=False)
  folderPath=folderPath+"audio+"+str(formatted_time).replace(" ","_")+".mp3"
  globalfilepath=folderPath
  gtts_obj.save(folderPath)

#Calling function to test
audioWithFileSave(text_to_say,language,folderPath)

#@title Playing audio file in google colab
from IPython.display import Audio
Audio(globalfilepath)

